package de.unisaarland.cs.se.selab.systemtest.selab25.farm

import de.unisaarland.cs.se.selab.systemtest.selab25.utils.FarmExtension

/**
 * Autogenerated Farm system test
 */
class FarmeveryplantationTwo : FarmExtension() {
    override val name = "FarmeveryplantationTwo"
    override val description = "Farmeveryplantation from 15 for 4"

    override val farms = "FarmControllertest/farmeveryplantation.json"
    override val scenario = "FarmControllertest/scenario.json"
    override val map = "FarmControllertest/mapeveryplantation.json"

    override val logLevel = "DEBUG"
    override val maxTicks = 2
    override val startYearTick = 15

    override suspend fun run() {
        assertNextLine("[INFO] Initialization Info: mapeveryplantation.json successfully parsed and validated.")
        assertNextLine("[INFO] Initialization Info: farmeveryplantation.json successfully parsed and validated.")
        assertNextLine("[INFO] Initialization Info: scenario.json successfully parsed and validated.")
        assertNextLine("[INFO] Simulation Info: Simulation started at tick 15 within the year.")
        assertNextLine("[INFO] Simulation Info: Tick 0 started at tick 15 within the year.")
        assertNextLine("[INFO] Soil Moisture: The soil moisture is below threshold in 0 FIELD and 0 PLANTATION tiles.")
        assertNextLine("[IMPORTANT] Farm: Farm 0 starts its actions.")
        assertNextLine(
            "[DEBUG] Farm: Farm 0 has the following active sowing plans it intends to pu" +
                "rsue in this tick: ."
        )
        assertNextLine("[IMPORTANT] Farm Action: Machine 3 performs HARVESTING on tile 1 for 7 days.")
        assertNextLine("[IMPORTANT] Farm Harvest: Machine 3 has collected 360000 g of CHERRY harvest.")
        assertNextLine("[IMPORTANT] Farm Action: Machine 3 performs HARVESTING on tile 2 for 7 days.")
        assertNextLine("[IMPORTANT] Farm Harvest: Machine 3 has collected 360000 g of CHERRY harvest.")
        assertNextLine("[IMPORTANT] Farm Machine: Machine 3 is finished and returns to the shed at 0.")
        assertNextLine("[IMPORTANT] Farm Machine: Machine 3 unloads 720000 g of CHERRY harvest in the shed.")
        assertNextLine("[IMPORTANT] Farm Action: Machine 2 performs CUTTING on tile 7 for 2 days.")
        assertNextLine("[IMPORTANT] Farm Action: Machine 2 performs CUTTING on tile 8 for 2 days.")
        assertNextLine("[IMPORTANT] Farm Machine: Machine 2 is finished and returns to the shed at 0.")
        assertNextLine("[IMPORTANT] Farm: Farm 0 finished its actions.")
        assertNextLine("[INFO] Harvest Estimate: Harvest estimate on tile 5 changed to 1115370 g of APPLE.")
        assertNextLine("[INFO] Harvest Estimate: Harvest estimate on tile 6 changed to 1115370 g of APPLE.")
        assertNextLine("[INFO] Simulation Info: Tick 1 started at tick 16 within the year.")
        assertNextLine("[INFO] Soil Moisture: The soil moisture is below threshold in 0 FIELD and 0 PLANTATION tiles.")
        assertNextLine("[IMPORTANT] Farm: Farm 0 starts its actions.")
        assertNextLine(
            "[DEBUG] Farm: Farm 0 has the following active sowi" +
                "ng plans it intends to pursue in this tick: ."
        )
        assertNextLine("[IMPORTANT] Farm Action: Machine 0 performs HARVESTING on tile 3 for 2 days.")
        assertNextLine("[IMPORTANT] Farm Harvest: Machine 0 has collected 800000 g of ALMOND harvest.")
        assertNextLine("[IMPORTANT] Farm Action: Machine 0 performs HARVESTING on tile 4 for 2 days.")
        assertNextLine("[IMPORTANT] Farm Harvest: Machine 0 has collected 800000 g of ALMOND harvest.")
        assertNextLine("[IMPORTANT] Farm Machine: Machine 0 is finished and returns to the shed at 0.")
        assertNextLine("[IMPORTANT] Farm Machine: Machine 0 unloads 1600000 g of ALMOND harvest in the shed.")
        assertNextLine("[IMPORTANT] Farm: Farm 0 finished its actions.")
        assertNextLine("[INFO] Harvest Estimate: Harvest estimate on tile 5 changed to 731793 g of APPLE.")
        assertNextLine("[INFO] Harvest Estimate: Harvest estimate on tile 6 changed to 731793 g of APPLE.")
        assertNextLine("[IMPORTANT] Simulation Info: Simulation ended at tick 2.")
        assertNextLine("[IMPORTANT] Simulation Info: Simulation statistics are calculated.")
        assertNextLine("[IMPORTANT] Simulation Statistics: Farm 0 collected 2320000 g of harvest.")
        assertNextLine("[IMPORTANT] Simulation Statistics: Total amount of POTATO harvested: 0 g.")
        assertNextLine("[IMPORTANT] Simulation Statistics: Total amount of WHEAT harvested: 0 g.")
        assertNextLine("[IMPORTANT] Simulation Statistics: Total amount of OAT harvested: 0 g.")
        assertNextLine("[IMPORTANT] Simulation Statistics: Total amount of PUMPKIN harvested: 0 g.")
        assertNextLine("[IMPORTANT] Simulation Statistics: Total amount of APPLE harvested: 0 g.")
        assertNextLine("[IMPORTANT] Simulation Statistics: Total amount of GRAPE harvested: 0 g.")
        assertNextLine("[IMPORTANT] Simulation Statistics: Total amount of ALMOND harvested: 1600000 g.")
        assertNextLine("[IMPORTANT] Simulation Statistics: Total amount of CHERRY harvested: 720000 g.")
        assertNextLine(
            "[IMPORTANT] Simulation Statistics: Total harvest estimate still in fields and planta" +
                "tions: 3863586 g."
        )
    }
}
