package de.unisaarland.cs.se.selab.systemtest.selab25.farm

import de.unisaarland.cs.se.selab.systemtest.selab25.utils.FarmExtension

/**
 * Autogenerated Farm system test
 */
class FarmeveryplantationThree : FarmExtension() {
    override val name = "FarmeveryplantationThree"
    override val description = "Farmeveryplantatio from 17 for 2"

    override val farms = "FarmControllertest/farmeveryplantation.json"
    override val scenario = "FarmControllertest/scenario.json"
    override val map = "FarmControllertest/mapeveryplantation.json"

    override val logLevel = "DEBUG"
    override val maxTicks = 2
    override val startYearTick = 17

    override suspend fun run() {
        assertNextLine("[INFO] Initialization Info: mapeveryplantation.json successfully parsed and validated.")
        assertNextLine("[INFO] Initialization Info: farmeveryplantation.json successfully parsed and validated.")
        assertNextLine("[INFO] Initialization Info: scenario.json successfully parsed and validated.")
        assertNextLine("[INFO] Simulation Info: Simulation started at tick 17 within the year.")
        assertNextLine("[INFO] Simulation Info: Tick 0 started at tick 17 within the year.")
        assertNextLine("[INFO] Soil Moisture: The soil moisture is below threshold in 0 FIELD and 0 PLANTATION tiles.")
        assertNextLine("[IMPORTANT] Farm: Farm 0 starts its actions.")
        assertNextLine(
            "[DEBUG] Farm: Farm 0 has the following active so" +
                "wing plans it intends to pursue in this tick: ."
        )
        assertNextLine("[IMPORTANT] Farm Action: Machine 0 performs HARVESTING on tile 3 for 2 days.")
        assertNextLine("[IMPORTANT] Farm Harvest: Machine 0 has collected 800000 g of ALMOND harvest.")
        assertNextLine("[IMPORTANT] Farm Action: Machine 0 performs HARVESTING on tile 4 for 2 days.")
        assertNextLine("[IMPORTANT] Farm Harvest: Machine 0 has collected 800000 g of ALMOND harvest.")
        assertNextLine("[IMPORTANT] Farm Machine: Machine 0 is finished and returns to the shed at 0.")
        assertNextLine("[IMPORTANT] Farm Machine: Machine 0 unloads 1600000 g of ALMOND harvest in the shed.")
        assertNextLine("[IMPORTANT] Farm Action: Machine 6 performs HARVESTING on tile 5 for 6 days.")
        assertNextLine("[IMPORTANT] Farm Harvest: Machine 6 has collected 1700000 g of APPLE harvest.")
        assertNextLine("[IMPORTANT] Farm Action: Machine 6 performs HARVESTING on tile 6 for 6 days.")
        assertNextLine("[IMPORTANT] Farm Harvest: Machine 6 has collected 1700000 g of APPLE harvest.")
        assertNextLine("[IMPORTANT] Farm Machine: Machine 6 is finished and returns to the shed at 0.")
        assertNextLine("[IMPORTANT] Farm Machine: Machine 6 unloads 3400000 g of APPLE harvest in the shed.")
        assertNextLine("[IMPORTANT] Farm Action: Machine 2 performs HARVESTING on tile 7 for 2 days.")
        assertNextLine("[IMPORTANT] Farm Harvest: Machine 2 has collected 1200000 g of GRAPE harvest.")
        assertNextLine("[IMPORTANT] Farm Action: Machine 2 performs HARVESTING on tile 8 for 2 days.")
        assertNextLine("[IMPORTANT] Farm Harvest: Machine 2 has collected 1200000 g of GRAPE harvest.")
        assertNextLine("[IMPORTANT] Farm Machine: Machine 2 is finished and returns to the shed at 0.")
        assertNextLine("[IMPORTANT] Farm Machine: Machine 2 unloads 2400000 g of GRAPE harvest in the shed.")
        assertNextLine("[IMPORTANT] Farm: Farm 0 finished its actions.")
        assertNextLine("[INFO] Simulation Info: Tick 1 started at tick 18 within the year.")
        assertNextLine("[INFO] Soil Moisture: The soil moisture is below threshold in 0 FIELD and 0 PLANTATION tiles.")
        assertNextLine("[IMPORTANT] Farm: Farm 0 starts its actions.")
        assertNextLine(
            "[DEBUG] Farm: Farm 0 has the following active sowing plans it inten" +
                "ds to pursue in this tick: ."
        )
        assertNextLine("[IMPORTANT] Farm: Farm 0 finished its actions.")
        assertNextLine("[IMPORTANT] Simulation Info: Simulation ended at tick 2.")
        assertNextLine("[IMPORTANT] Simulation Info: Simulation statistics are calculated.")
        assertNextLine("[IMPORTANT] Simulation Statistics: Farm 0 collected 7400000 g of harvest.")
        assertNextLine("[IMPORTANT] Simulation Statistics: Total amount of POTATO harvested: 0 g.")
        assertNextLine("[IMPORTANT] Simulation Statistics: Total amount of WHEAT harvested: 0 g.")
        assertNextLine("[IMPORTANT] Simulation Statistics: Total amount of OAT harvested: 0 g.")
        assertNextLine("[IMPORTANT] Simulation Statistics: Total amount of PUMPKIN harvested: 0 g.")
        assertNextLine("[IMPORTANT] Simulation Statistics: Total amount of APPLE harvested: 3400000 g.")
        assertNextLine("[IMPORTANT] Simulation Statistics: Total amount of GRAPE harvested: 2400000 g.")
        assertNextLine("[IMPORTANT] Simulation Statistics: Total amount of ALMOND harvested: 1600000 g.")
        assertNextLine("[IMPORTANT] Simulation Statistics: Total amount of CHERRY harvested: 0 g.")
        assertNextLine(
            "[IMPORTANT] Simulation Statistics: Total harvest estimate still in fields and planta" +
                "tions: 2400000 g."
        )
    }
}
