package de.unisaarland.cs.se.selab.systemtest.selab25.farm

import de.unisaarland.cs.se.selab.systemtest.selab25.utils.FarmExtension

const val MTWHNVPX = "[IMPORTANT] Farm Action: Machine 0 performs MOWING on tile 3 for 2 days."
const val IFMOJLNX = "[IMPORTANT] Farm Machine: Machine 0 is finished and returns to the shed at 0."
const val BUHVONWK = "[IMPORTANT] Farm Action: Machine 6 performs MOWING on tile 5 for 6 days."
const val GNUPPRUH = "[IMPORTANT] Farm Machine: Machine 6 is finished and returns to the shed at 0."
const val OOATHITA = "[IMPORTANT] Farm Action: Machine 3 performs MOWING on tile 1 for 7 days."
const val FRPBNDDS = "[IMPORTANT] Farm Machine: Machine 3 is finished and returns to the shed at 0."
const val GODWFTCB = "[IMPORTANT] Farm: Farm 0 finished its actions."
const val BTILBWBU = "[IMPORTANT] Farm Action: Machine 3 performs HARVESTING on tile 1 for 7 days."
const val PUCBETFB = "[IMPORTANT] Farm Harvest: Machine 3 has collected 972000 g of CHERRY harvest."
const val HBJKVUPM = "[IMPORTANT] Farm Machine: Machine 3 unloads 972000 g of CHERRY harvest in the shed."
const val RPSQTMRF = "[IMPORTANT] Farm Action: Machine 0 performs IRRIGATING on tile 3 for 2 days."
const val KYNYJYJU = "[IMPORTANT] Farm Action: Machine 2 performs MOWING on tile 7 for 2 days."
const val EYCHHCQT = "[IMPORTANT] Farm Machine: Machine 2 is finished and returns to the shed at 0."
const val RLEKTWMH = "[IMPORTANT] Farm Action: Machine 2 performs CUTTING on tile 7 for 2 days."
const val ZQGXEFQG = "[IMPORTANT] Farm Action: Machine 2 performs IRRIGATING on tile 7 for 2 days."
const val BYHJITMA = "[IMPORTANT] Farm Action: Machine 3 performs IRRIGATING on tile 1 for 7 days."
const val NITNNMXC = "[IMPORTANT] Farm Action: Machine 0 performs HARVESTING on tile 3 for 2 days."
const val CAXROYCU = "[IMPORTANT] Farm Harvest: Machine 0 has collected 524880 g of ALMOND harvest."
const val ARIITCPW = "[IMPORTANT] Farm Machine: Machine 0 unloads 524880 g of ALMOND harvest in the shed."
const val LNKAALPL = "[IMPORTANT] Farm Action: Machine 6 performs IRRIGATING on tile 5 for 6 days."
const val NOXPTWCV = "[IMPORTANT] Farm Action: Machine 6 performs HARVESTING on tile 5 for 6 days."
const val MOQYWXSC = "[IMPORTANT] Farm Harvest: Machine 6 has collected 135599 g of APPLE harvest."
const val SBBXRTAF = "[IMPORTANT] Farm Machine: Machine 6 unloads 135599 g of APPLE harvest in the shed."
const val FPBLRGRV = "[IMPORTANT] Farm Action: Machine 2 performs HARVESTING on tile 7 for 2 days."
const val SHXQRHCM = "[IMPORTANT] Farm Harvest: Machine 2 has collected 1200000 g of GRAPE harvest."
const val QPNKIOIN = "[IMPORTANT] Farm Machine: Machine 2 unloads 1200000 g of GRAPE harvest in the shed."
const val IGEVUGZA = "[IMPORTANT] Simulation Info: Simulation ended at tick 10."

/**
 * Autogenerated Farm system test
 */
class Farmjump : FarmExtension() {
    override val name = "Farmjump"
    override val description = "Farmjump"

    override val farms = "FarmControllertest/farmjump.json"
    override val scenario = "FarmControllertest/scenario.json"
    override val map = "FarmControllertest/mapjump.json"

    override val logLevel = "IMPORTANT"
    override val maxTicks = 10
    override val startYearTick = 11

    override suspend fun run() {
        skipUntilFarm()
        assertNextLine(MTWHNVPX)
        assertNextLine(IFMOJLNX)
        assertNextLine(BUHVONWK)
        assertNextLine(GNUPPRUH)
        assertNextLine(OOATHITA)
        assertNextLine(FRPBNDDS)
        assertNextLine(GODWFTCB)
        skipUntilFarm()
        assertNextLine(GODWFTCB)
        skipUntilFarm()
        assertNextLine(BTILBWBU)
        assertNextLine(PUCBETFB)
        assertNextLine(FRPBNDDS)
        assertNextLine(HBJKVUPM)
        assertNextLine(RPSQTMRF)
        assertNextLine(IFMOJLNX)
        assertNextLine(KYNYJYJU)
        assertNextLine(EYCHHCQT)
        assertNextLine(GODWFTCB)
        skipUntilFarm()
        assertNextLine(RLEKTWMH)
        assertNextLine(EYCHHCQT)
        assertNextLine(GODWFTCB)
        skipUntilFarm()
        assertNextLine(ZQGXEFQG)
        assertNextLine(EYCHHCQT)
        assertNextLine(BYHJITMA)
        assertNextLine(FRPBNDDS)
        assertNextLine(GODWFTCB)
        skipUntilFarm()
        assertNextLine(NITNNMXC)
        assertNextLine(CAXROYCU)
        assertNextLine(IFMOJLNX)
        assertNextLine(ARIITCPW)
        assertNextLine(LNKAALPL)
        assertNextLine(GNUPPRUH)
        assertNextLine(GODWFTCB)
        skipUntilFarm()
        assertNextLine(NOXPTWCV)
        assertNextLine(MOQYWXSC)
        assertNextLine(GNUPPRUH)
        assertNextLine(SBBXRTAF)
        assertNextLine(FPBLRGRV)
        assertNextLine(SHXQRHCM)
        assertNextLine(EYCHHCQT)
        assertNextLine(QPNKIOIN)
        assertNextLine(RPSQTMRF)
        n1()
    }
    suspend fun n1() {
        assertNextLine(IFMOJLNX)
        assertNextLine(GODWFTCB)
        skipUntilFarm()
        assertNextLine(GODWFTCB)
        skipUntilFarm()
        assertNextLine(ZQGXEFQG)
        assertNextLine(EYCHHCQT)
        assertNextLine(GODWFTCB)
        skipUntilFarm()
        assertNextLine(RPSQTMRF)
        assertNextLine(IFMOJLNX)
        assertNextLine(BYHJITMA)
        assertNextLine(FRPBNDDS)
        assertNextLine(GODWFTCB)
        assertNextLine(IGEVUGZA)
    }
}
