package de.unisaarland.cs.se.selab.systemtest.selab25.farm

import de.unisaarland.cs.se.selab.systemtest.selab25.utils.FarmExtension

const val LRDFGFVJ = "[DEBUG] Farm: Farm 0 has the following active sowing plans it intends to pursue in this ti" +
    "ck: 5."
const val CWEDYFXG = "[IMPORTANT] Farm Action: Machine 0 performs SOWING on tile 1 for 6 days."
const val NVEYXLRQ = "[IMPORTANT] Farm Sowing: Machine 0 has sowed OAT according to sowing plan 5."
const val JGNASZXU = "[IMPORTANT] Farm Action: Machine 0 performs SOWING on tile 2 for 6 days."
const val ZCURXFPT = "[IMPORTANT] Farm Machine: Machine 0 is finished and returns to the shed at 0."
const val QVASSSZR = "[IMPORTANT] Farm: Farm 0 finished its actions."
const val EJDZDNIJ = "[INFO] Harvest Estimate: Harvest estimate on tile 1 changed to 1080000 g of OAT."
const val BKUAQPCB = "[INFO] Harvest Estimate: Harvest estimate on tile 2 changed to 1080000 g of OAT."
const val YHKQKDGO = "[DEBUG] Farm: Farm 0 has the following active sowing plans it intends to pursue in this tick: ."
const val OKUVOIYE = "[IMPORTANT] Farm Action: Machine 6 performs WEEDING on tile 1 for 6 days."
const val LPGBXXNG = "[IMPORTANT] Farm Action: Machine 6 performs WEEDING on tile 2 for 6 days."
const val YNJIAMKE = "[IMPORTANT] Farm Machine: Machine 6 is finished and returns to the shed at 0."
const val KOSROXZV = "[INFO] Harvest Estimate: Harvest estimate on tile 1 changed to 874800 g of OAT."
const val HVQAQSXH = "[INFO] Harvest Estimate: Harvest estimate on tile 2 changed to 874800 g of OAT."
const val OHPEAEQV = "[INFO] Harvest Estimate: Harvest estimate on tile 1 changed to 708588 g of OAT."
const val YQVNMEKD = "[INFO] Harvest Estimate: Harvest estimate on tile 2 changed to 708588 g of OAT."
const val RKHXKASD = "[INFO] Harvest Estimate: Harvest estimate on tile 1 changed to 516560 g of OAT."
const val YDZVAFQS = "[INFO] Harvest Estimate: Harvest estimate on tile 2 changed to 516560 g of OAT."
const val LOAZXTFN = "[IMPORTANT] Simulation Info: Simulation ended at tick 4."
const val AATNBUMB = "[IMPORTANT] Simulation Info: Simulation statistics are calculated."
const val WFFGKCND = "[IMPORTANT] Simulation Statistics: Farm 0 collected 0 g of harvest."
const val SFXMYPUM = "[IMPORTANT] Simulation Statistics: Total amount of POTATO harvested: 0 g."
const val DPTWVVUM = "[IMPORTANT] Simulation Statistics: Total amount of WHEAT harvested: 0 g."
const val WWJNFECD = "[IMPORTANT] Simulation Statistics: Total amount of OAT harvested: 0 g."
const val RXVLZJZJ = "[IMPORTANT] Simulation Statistics: Total amount of PUMPKIN harvested: 0 g."
const val BKACJGBH = "[IMPORTANT] Simulation Statistics: Total amount of APPLE harvested: 0 g."
const val MKIJVVRS = "[IMPORTANT] Simulation Statistics: Total amount of GRAPE harvested: 0 g."
const val ZKEDKERO = "[IMPORTANT] Simulation Statistics: Total amount of ALMOND harvested: 0 g."
const val LBQRPEGD = "[IMPORTANT] Simulation Statistics: Total amount of CHERRY harvested: 0 g."
const val UADBVCGI = "[IMPORTANT] Simulation Statistics: Total harvest estimate still in fields and planta" +
    "tions: 1033120 g."

/**
 * Autogenerated Farm system test
 */
class FarmSimpleSow : FarmExtension() {
    override val name = "FarmSimplesow"
    override val description = "Farm1"

    override val farms = "FarmControllertest/farm1.json"
    override val scenario = "FarmControllertest/scenario.json"
    override val map = "FarmControllertest/map2.json"

    override val logLevel = "DEBUG"
    override val maxTicks = 4
    override val startYearTick = 6

    override suspend fun run() {
        skipUntilFarm()
        assertNextLine(LRDFGFVJ)
        assertNextLine(CWEDYFXG)
        assertNextLine(NVEYXLRQ)
        assertNextLine(JGNASZXU)
        assertNextLine(NVEYXLRQ)
        assertNextLine(ZCURXFPT)
        assertNextLine(QVASSSZR)
        assertNextLine(EJDZDNIJ)
        assertNextLine(BKUAQPCB)
        skipUntilFarm()
        assertNextLine(YHKQKDGO)
        assertNextLine(OKUVOIYE)
        assertNextLine(LPGBXXNG)
        assertNextLine(YNJIAMKE)
        assertNextLine(QVASSSZR)
        assertNextLine(KOSROXZV)
        assertNextLine(HVQAQSXH)
        skipUntilFarm()
        assertNextLine(YHKQKDGO)
        assertNextLine(OKUVOIYE)
        assertNextLine(LPGBXXNG)
        assertNextLine(YNJIAMKE)
        assertNextLine(QVASSSZR)
        assertNextLine(OHPEAEQV)
        assertNextLine(YQVNMEKD)
        skipUntilFarm()
        assertNextLine(YHKQKDGO)
        assertNextLine(OKUVOIYE)
        assertNextLine(LPGBXXNG)
        assertNextLine(YNJIAMKE)
        assertNextLine(QVASSSZR)
        assertNextLine(RKHXKASD)
        assertNextLine(YDZVAFQS)
        assertNextLine(LOAZXTFN)
        assertNextLine(AATNBUMB)
        assertNextLine(WFFGKCND)
        assertNextLine(SFXMYPUM)
        assertNextLine(DPTWVVUM)
        assertNextLine(WWJNFECD)
        assertNextLine(RXVLZJZJ)
        assertNextLine(BKACJGBH)
        assertNextLine(MKIJVVRS)
        assertNextLine(ZKEDKERO)
        assertNextLine(LBQRPEGD)
        assertNextLine(UADBVCGI)
    }
}
