package de.unisaarland.cs.se.selab.systemtest.selab25.farm

import de.unisaarland.cs.se.selab.systemtest.selab25.utils.FarmExtension

const val QZEJGRRS = "[DEBUG] Farm: Farm 0 has the following active sowing plans it intends to pursue in this tick: 9."
const val DFZZAXPI = "[IMPORTANT] Farm: Farm 0 finished its actions."
const val SMTNQVIT = "[DEBUG] Farm: Farm 0 has the following active sowing plans it intends to pur" +
    "sue in this tick: 5,9."
const val QKSQTFBI = "[IMPORTANT] Farm Action: Machine 0 performs SOWING on tile 1 for 4 days."
const val PHPEZLUY = "[IMPORTANT] Farm Sowing: Machine 0 has sowed OAT according to sowing plan 9."
const val NRWCMWAS = "[IMPORTANT] Farm Action: Machine 0 performs SOWING on tile 3 for 4 days."
const val UJYDIHLC = "[IMPORTANT] Farm Machine: Machine 0 is finished and returns to the shed at 0."
const val OFNPZJNZ = "[DEBUG] Harvest Estimate: Required actions on tile 1 were not performed: IRRIGATING."
const val LFFMJNWW = "[INFO] Harvest Estimate: Harvest estimate on tile 1 changed to 1079950 g of OAT."
const val JCYMMKCI = "[DEBUG] Harvest Estimate: Required actions on tile 3 were not performed: IRRIGATING."
const val OHFXULUV = "[INFO] Harvest Estimate: Harvest estimate on tile 3 changed to 1079950 g of OAT."
const val VCDIXRNK = "[DEBUG] Farm: Farm 0 has the following active sowing plans it intends to pursue in this tick: 5."
const val SGPFJYDL = "[IMPORTANT] Farm Action: Machine 6 performs IRRIGATING on tile 1 for 6 days."
const val THZQNVVA = "[IMPORTANT] Farm Action: Machine 6 performs IRRIGATING on tile 3 for 6 days."
const val HTWHFEWN = "[IMPORTANT] Farm Machine: Machine 6 is finished and returns to the shed at 0."
const val JJIXQMBJ = "[DEBUG] Harvest Estimate: Required actions on tile 1 were not performed: WEEDING."
const val DLYNPMDH = "[INFO] Harvest Estimate: Harvest estimate on tile 1 changed to 787283 g of OAT."
const val CZUFPPHJ = "[DEBUG] Harvest Estimate: Required actions on tile 3 were not performed: WEEDING."
const val ENUPLBYY = "[INFO] Harvest Estimate: Harvest estimate on tile 3 changed to 787283 g of OAT."
const val DBDQUIVH = "[IMPORTANT] Farm Action: Machine 6 performs WEEDING on tile 1 for 6 days."
const val GSILTGEU = "[IMPORTANT] Farm Action: Machine 6 performs WEEDING on tile 3 for 6 days."
const val PBBHZRSW = "[INFO] Harvest Estimate: Harvest estimate on tile 1 changed to 637698 g of OAT."
const val JIAHELYJ = "[INFO] Harvest Estimate: Harvest estimate on tile 3 changed to 637698 g of OAT."
const val QXTGCFKU = "[INFO] Harvest Estimate: Harvest estimate on tile 1 changed to 464881 g of OAT."
const val HKTXFNZI = "[INFO] Harvest Estimate: Harvest estimate on tile 3 changed to 464881 g of OAT."
const val YHRDYVND = "[INFO] Harvest Estimate: Harvest estimate on tile 1 changed to 338896 g of OAT."
const val ZGGYXDPQ = "[INFO] Harvest Estimate: Harvest estimate on tile 3 changed to 338896 g of OAT."
const val BPJKWHOB = "[INFO] Harvest Estimate: Harvest estimate on tile 1 changed to 247054 g of OAT."
const val RCSLDOIE = "[INFO] Harvest Estimate: Harvest estimate on tile 3 changed to 247054 g of OAT."
const val UHSIORFI = "[INFO] Harvest Estimate: Harvest estimate on tile 1 changed to 180101 g of OAT."
const val TJMZRUJD = "[INFO] Harvest Estimate: Harvest estimate on tile 3 changed to 180101 g of OAT."
const val FTJBPFFW = "[IMPORTANT] Farm Action: Machine 6 performs HARVESTING on tile 1 for 6 days."
const val NMHRTRKX = "[IMPORTANT] Farm Harvest: Machine 6 has collected 180101 g of OAT harvest."
const val FIIYCZEA = "[IMPORTANT] Farm Action: Machine 6 performs HARVESTING on tile 3 for 6 days."
const val XPITAJCE = "[IMPORTANT] Farm Machine: Machine 6 unloads 360202 g of OAT harvest in the shed."
const val PQHBEDRZ = "[IMPORTANT] Simulation Info: Simulation ended at tick 13."
const val GEBVCQGN = "[IMPORTANT] Simulation Info: Simulation statistics are calculated."
const val NYFQGYFS = "[IMPORTANT] Simulation Statistics: Farm 0 collected 360202 g of harvest."
const val KZSRNAKO = "[IMPORTANT] Simulation Statistics: Total amount of POTATO harvested: 0 g."
const val FYPTOXBF = "[IMPORTANT] Simulation Statistics: Total amount of WHEAT harvested: 0 g."
const val ESVVEXOZ = "[IMPORTANT] Simulation Statistics: Total amount of OAT harvested: 360202 g."
const val ZXMWRIQX = "[IMPORTANT] Simulation Statistics: Total amount of PUMPKIN harvested: 0 g."
const val GCUUJAFL = "[IMPORTANT] Simulation Statistics: Total amount of APPLE harvested: 0 g."
const val HJPKXINV = "[IMPORTANT] Simulation Statistics: Total amount of GRAPE harvested: 0 g."
const val BETMDAZZ = "[IMPORTANT] Simulation Statistics: Total amount of ALMOND harvested: 0 g."
const val TPVXSUWQ = "[IMPORTANT] Simulation Statistics: Total amount of CHERRY harvested: 0 g."
const val LFIGKMXX = "[IMPORTANT] Simulation Statistics: Total harvest estimate still in fields and plantations: 0 g."

/**
 * Autogenerated Farm system test
 */
class Farmsowone : FarmExtension() {
    override val name = "Farmsowone"
    override val description = "Farmsowone"

    override val farms = "FarmControllertest/farmsowone.json"
    override val scenario = "FarmControllertest/scenario.json"
    override val map = "FarmControllertest/mapsowone.json"

    override val logLevel = "DEBUG"
    override val maxTicks = 13
    override val startYearTick = 1

    override suspend fun run() {
        skipUntilFarm()
        assertNextLine(QZEJGRRS)
        assertNextLine(DFZZAXPI)
        skipUntilFarm()
        assertNextLine(SMTNQVIT)
        assertNextLine(DFZZAXPI)
        skipUntilFarm()
        assertNextLine(SMTNQVIT)
        assertNextLine(DFZZAXPI)
        skipUntilFarm()
        assertNextLine(SMTNQVIT)
        assertNextLine(DFZZAXPI)
        skipUntilFarm()
        assertNextLine(SMTNQVIT)
        assertNextLine(DFZZAXPI)
        skipUntilFarm()
        assertNextLine(SMTNQVIT)
        assertNextLine(QKSQTFBI)
        assertNextLine(PHPEZLUY)
        assertNextLine(NRWCMWAS)
        assertNextLine(PHPEZLUY)
        assertNextLine(UJYDIHLC)
        assertNextLine(DFZZAXPI)
        assertNextLine(OFNPZJNZ)
        assertNextLine(LFFMJNWW)
        assertNextLine(JCYMMKCI)
        assertNextLine(OHFXULUV)
        skipUntilFarm()
        assertNextLine(VCDIXRNK)
        assertNextLine(SGPFJYDL)
        assertNextLine(THZQNVVA)
        assertNextLine(HTWHFEWN)
        assertNextLine(DFZZAXPI)
        assertNextLine(JJIXQMBJ)
        assertNextLine(DLYNPMDH)
        assertNextLine(CZUFPPHJ)
        assertNextLine(ENUPLBYY)
        skipUntilFarm()
        assertNextLine(VCDIXRNK)
        assertNextLine(DBDQUIVH)
        assertNextLine(GSILTGEU)
        assertNextLine(HTWHFEWN)
        n1()
    }
    suspend fun n1() {
        assertNextLine(DFZZAXPI)
        assertNextLine(PBBHZRSW)
        assertNextLine(JIAHELYJ)
        skipUntilFarm()
        assertNextLine(VCDIXRNK)
        assertNextLine(DBDQUIVH)
        assertNextLine(GSILTGEU)
        assertNextLine(HTWHFEWN)
        assertNextLine(DFZZAXPI)
        assertNextLine(QXTGCFKU)
        assertNextLine(HKTXFNZI)
        skipUntilFarm()
        assertNextLine(VCDIXRNK)
        assertNextLine(DFZZAXPI)
        assertNextLine(YHRDYVND)
        assertNextLine(ZGGYXDPQ)
        skipUntilFarm()
        assertNextLine(VCDIXRNK)
        assertNextLine(SGPFJYDL)
        assertNextLine(THZQNVVA)
        assertNextLine(HTWHFEWN)
        assertNextLine(DFZZAXPI)
        assertNextLine(BPJKWHOB)
        assertNextLine(RCSLDOIE)
        skipUntilFarm()
        assertNextLine(VCDIXRNK)
        assertNextLine(DFZZAXPI)
        assertNextLine(UHSIORFI)
        assertNextLine(TJMZRUJD)
        skipUntilFarm()
        assertNextLine(VCDIXRNK)
        assertNextLine(FTJBPFFW)
        assertNextLine(NMHRTRKX)
        assertNextLine(FIIYCZEA)
        assertNextLine(NMHRTRKX)
        assertNextLine(HTWHFEWN)
        assertNextLine(XPITAJCE)
        assertNextLine(DFZZAXPI)
        assertNextLine(PQHBEDRZ)
        assertNextLine(GEBVCQGN)
        assertNextLine(NYFQGYFS)
        assertNextLine(KZSRNAKO)
        assertNextLine(FYPTOXBF)
        assertNextLine(ESVVEXOZ)
        assertNextLine(ZXMWRIQX)
        assertNextLine(GCUUJAFL)
        assertNextLine(HJPKXINV)
        assertNextLine(BETMDAZZ)
        assertNextLine(TPVXSUWQ)
        assertNextLine(LFIGKMXX)
    }
}
