package de.unisaarland.cs.se.selab.systemtest.selab25.farm

import de.unisaarland.cs.se.selab.systemtest.selab25.utils.FarmExtension

const val NNIPXOQG = "[DEBUG] Farm: Farm 0 has the following active sowing plans it intends to pursue in this tick: 9."
const val BRRWVOSW = "[IMPORTANT] Farm Action: Machine 0 performs SOWING on tile 1 for 4 days."
const val GYKCNSCE = "[IMPORTANT] Farm Sowing: Machine 0 has sowed OAT according to sowing plan 9."
const val FSVTLWJW = "[IMPORTANT] Farm Action: Machine 0 performs SOWING on tile 3 for 4 days."
const val PYIOXYXO = "[IMPORTANT] Farm Machine: Machine 0 is finished and returns to the shed at 0."
const val LUTSPXRF = "[IMPORTANT] Farm: Farm 0 finished its actions."
const val QREPJVMG = "[INFO] Harvest Estimate: Harvest estimate on tile 1 changed to 1080000 g of OAT."
const val ZWPUXOVU = "[INFO] Harvest Estimate: Harvest estimate on tile 2 changed to 1239300 g of APPLE."
const val OTSZHQYL = "[INFO] Harvest Estimate: Harvest estimate on tile 3 changed to 1080000 g of OAT."
const val TPLDPCZE = "[DEBUG] Farm: Farm 0 has the following active sowing plans it intends to pursue in this tick: 5."
const val OLEXRSQJ = "[IMPORTANT] Farm Action: Machine 6 performs WEEDING on tile 1 for 6 days."
const val MDQJYXLH = "[IMPORTANT] Farm Action: Machine 6 performs WEEDING on tile 3 for 6 days."
const val HJBWYGLV = "[IMPORTANT] Farm Machine: Machine 6 is finished and returns to the shed at 0."
const val OVEDYMFL = "[INFO] Harvest Estimate: Harvest estimate on tile 1 changed to 874800 g of OAT."
const val HVEBXGCL = "[INFO] Harvest Estimate: Harvest estimate on tile 2 changed to 903449 g of APPLE."
const val EMDZTHMO = "[INFO] Harvest Estimate: Harvest estimate on tile 3 changed to 874800 g of OAT."
const val PHZNSLWA = "[INFO] Harvest Estimate: Harvest estimate on tile 1 changed to 708588 g of OAT."
const val MGTDFYQU = "[INFO] Harvest Estimate: Harvest estimate on tile 2 changed to 658613 g of APPLE."
const val BXCOPDKO = "[INFO] Harvest Estimate: Harvest estimate on tile 3 changed to 708588 g of OAT."
const val RQRUFPIS = "[IMPORTANT] Farm Action: Machine 6 performs IRRIGATING on tile 1 for 6 days."
const val QPUAKHJH = "[IMPORTANT] Farm Action: Machine 6 performs IRRIGATING on tile 3 for 6 days."
const val YWXQMSXD = "[DEBUG] Harvest Estimate: Required actions on tile 1 were not performed: WEEDING."
const val VDZEQAUQ = "[INFO] Harvest Estimate: Harvest estimate on tile 1 changed to 464904 g of OAT."
const val RQRCAOVE = "[INFO] Harvest Estimate: Harvest estimate on tile 2 changed to 432114 g of APPLE."
const val UBKMTMUJ = "[DEBUG] Harvest Estimate: Required actions on tile 3 were not performed: WEEDING."
const val KCXVSOBH = "[INFO] Harvest Estimate: Harvest estimate on tile 3 changed to 464904 g of OAT."
const val QVSIPFDW = "[INFO] Harvest Estimate: Harvest estimate on tile 1 changed to 338913 g of OAT."
const val ZKWYSUXL = "[INFO] Harvest Estimate: Harvest estimate on tile 2 changed to 283508 g of APPLE."
const val PALSUZRI = "[INFO] Harvest Estimate: Harvest estimate on tile 3 changed to 338913 g of OAT."
const val GWCKGKSP = "[IMPORTANT] Simulation Info: Simulation ended at tick 5."
const val NVKLCYPW = "[IMPORTANT] Simulation Info: Simulation statistics are calculated."
const val GKOCBIBR = "[IMPORTANT] Simulation Statistics: Farm 0 collected 0 g of harvest."
const val EHTCNNOY = "[IMPORTANT] Simulation Statistics: Total amount of POTATO harvested: 0 g."
const val KMHQGDVJ = "[IMPORTANT] Simulation Statistics: Total amount of WHEAT harvested: 0 g."
const val KARDVEIC = "[IMPORTANT] Simulation Statistics: Total amount of OAT harvested: 0 g."

/**
 * Autogenerated Farm system test
 */
class Farmsowtwo : FarmExtension() {
    override val name = "Farmsowtwo"
    override val description = "Farmsowtwo"

    override val farms = "FarmControllertest/farmsowtwo.json"
    override val scenario = "FarmControllertest/scenario.json"
    override val map = "FarmControllertest/mapsowtwo.json"

    override val logLevel = "DEBUG"
    override val maxTicks = 5
    override val startYearTick = 6

    override suspend fun run() {
        skipUntilFarm()
        assertNextLine(NNIPXOQG)
        assertNextLine(BRRWVOSW)
        assertNextLine(GYKCNSCE)
        assertNextLine(FSVTLWJW)
        assertNextLine(GYKCNSCE)
        assertNextLine(PYIOXYXO)
        assertNextLine(LUTSPXRF)
        assertNextLine(QREPJVMG)
        assertNextLine(ZWPUXOVU)
        assertNextLine(OTSZHQYL)
        skipUntilFarm()
        assertNextLine(TPLDPCZE)
        assertNextLine(OLEXRSQJ)
        assertNextLine(MDQJYXLH)
        assertNextLine(HJBWYGLV)
        assertNextLine(LUTSPXRF)
        assertNextLine(OVEDYMFL)
        assertNextLine(HVEBXGCL)
        assertNextLine(EMDZTHMO)
        skipUntilFarm()
        assertNextLine(TPLDPCZE)
        assertNextLine(OLEXRSQJ)
        assertNextLine(MDQJYXLH)
        assertNextLine(HJBWYGLV)
        assertNextLine(LUTSPXRF)
        assertNextLine(PHZNSLWA)
        assertNextLine(MGTDFYQU)
        assertNextLine(BXCOPDKO)
        skipUntilFarm()
        assertNextLine(TPLDPCZE)
        assertNextLine(RQRUFPIS)
        assertNextLine(QPUAKHJH)
        assertNextLine(HJBWYGLV)
        assertNextLine(LUTSPXRF)
        assertNextLine(YWXQMSXD)
        assertNextLine(VDZEQAUQ)
        assertNextLine(RQRCAOVE)
        assertNextLine(UBKMTMUJ)
        assertNextLine(KCXVSOBH)
        skipUntilFarm()
        assertNextLine(TPLDPCZE)
        assertNextLine(LUTSPXRF)
        assertNextLine(QVSIPFDW)
        assertNextLine(ZKWYSUXL)
        assertNextLine(PALSUZRI)
        assertNextLine(GWCKGKSP)
        assertNextLine(NVKLCYPW)
        assertNextLine(GKOCBIBR)
        assertNextLine(EHTCNNOY)
        assertNextLine(KMHQGDVJ)
        assertNextLine(KARDVEIC)
    }
}
