package de.unisaarland.cs.se.selab.systemtest.selab25.farm

import de.unisaarland.cs.se.selab.systemtest.selab25.utils.FarmExtension

const val BZYDNYBW = "[DEBUG] Farm: Farm 0 has the following active sowing plans it intends to pursue in this tick: ."
const val CWVOPZOH = "[IMPORTANT] Farm: Farm 0 finished its actions."
const val RQTPYUIL = "[INFO] Harvest Estimate: Harvest estimate on tile 4 changed to 1239300 g of APPLE."
const val FSNMUUNO = "[DEBUG] Farm: Farm 0 has the following active sowing plans it intends to pursue in this tick: 5."
const val EKUXMPJM = "[IMPORTANT] Farm Action: Machine 0 performs SOWING on tile 3 for 4 days."
const val LDLOWTUW = "[IMPORTANT] Farm Sowing: Machine 0 has sowed OAT according to sowing plan 5."
const val VEHJNHZU = "[IMPORTANT] Farm Action: Machine 0 performs SOWING on tile 5 for 4 days."
const val ZXWWIYTN = "[IMPORTANT] Farm Machine: Machine 0 is finished and returns to the shed at 0."
const val QFWQKWAZ = "[INFO] Harvest Estimate: Harvest estimate on tile 3 changed to 777600 g of OAT."
const val VMFJDEVC = "[INFO] Harvest Estimate: Harvest estimate on tile 4 changed to 903449 g of APPLE."
const val CKVLYZPY = "[INFO] Harvest Estimate: Harvest estimate on tile 5 changed to 777600 g of OAT."
const val FIUIEDSP = "[IMPORTANT] Farm Action: Machine 6 performs WEEDING on tile 3 for 6 days."
const val ZQQUZUWJ = "[IMPORTANT] Farm Action: Machine 6 performs WEEDING on tile 5 for 6 days."
const val TJPCKVFU = "[IMPORTANT] Farm Machine: Machine 6 is finished and returns to the shed at 0."
const val FUJVVAZT = "[INFO] Harvest Estimate: Harvest estimate on tile 3 changed to 629856 g of OAT."
const val JFNPSNSG = "[INFO] Harvest Estimate: Harvest estimate on tile 4 changed to 658613 g of APPLE."

/**
 * Autogenerated Farm system test
 */
class Farmsowthree : FarmExtension() {
    override val name = "Farmsowthree"
    override val description = "Farmsowthree"

    override val farms = "FarmControllertest/farmsowthree.json"
    override val scenario = "FarmControllertest/scenario.json"
    override val map = "FarmControllertest/mapsowthree.json"

    override val logLevel = "DEBUG"
    override val maxTicks = 3
    override val startYearTick = 6

    override suspend fun run() {
        skipUntilFarm()
        assertNextLine(BZYDNYBW)
        assertNextLine(CWVOPZOH)
        assertNextLine(RQTPYUIL)
        skipUntilFarm()
        assertNextLine(FSNMUUNO)
        assertNextLine(EKUXMPJM)
        assertNextLine(LDLOWTUW)
        assertNextLine(VEHJNHZU)
        assertNextLine(LDLOWTUW)
        assertNextLine(ZXWWIYTN)
        assertNextLine(CWVOPZOH)
        assertNextLine(QFWQKWAZ)
        assertNextLine(VMFJDEVC)
        assertNextLine(CKVLYZPY)
        skipUntilFarm()
        assertNextLine(BZYDNYBW)
        assertNextLine(FIUIEDSP)
        assertNextLine(ZQQUZUWJ)
        assertNextLine(TJPCKVFU)
        assertNextLine(CWVOPZOH)
        assertNextLine(FUJVVAZT)
        assertNextLine(JFNPSNSG)
    }
}
